### ISSUE TITLE
libblingfiretokdll.dylib arm64e support

### ISSUE THREAD

**Issue by youyinnn** [microsoft/BlingFire#140]
Hi all, I am using M1 Mac env, and I got this. Can anyone help?

```bash
/Users/yinnnyou/miniconda3/envs/s2search/lib/python3.8/site-packages/blingfire
Traceback (most recent call last):
  File "s2search_example.py", line 3, in <module>
    from s2search.rank import S2Ranker
  File "/Users/yinnnyou/workspace/s2search/s2search/__init__.py", line 1, in <module>
    from s2search.features import *
  File "/Users/yinnnyou/workspace/s2search/s2search/features.py", line 5, in <module>
    from s2search.text import find_query_ngrams_in_text, fix_text, STOPWORDS
  File "/Users/yinnnyou/workspace/s2search/s2search/text.py", line 5, in <module>
    from blingfire import text_to_words
  File "/Users/yinnnyou/miniconda3/envs/s2search/lib/python3.8/site-packages/blingfire/__init__.py", line 20, in <module>
    blingfire = cdll.LoadLibrary(os.path.join(path, "libblingfiretokdll.dylib"))
  File "/Users/yinnnyou/miniconda3/envs/s2search/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/Users/yinnnyou/miniconda3/envs/s2search/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/yinnnyou/miniconda3/envs/s2search/lib/python3.8/site-packages/blingfire/libblingfiretokdll.dylib, 0x0006): tried: 
'/Users/yinnnyou/miniconda3/envs/s2search/lib/python3.8/site-packages/blingfire/libblingfiretokdll.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), 
'/usr/local/lib/libblingfiretokdll.dylib' (no such file), '/usr/lib/libblingfiretokdll.dylib' (no such file)
```

**Comment by lfoppiano** [comment]
See https://github.com/microsoft/BlingFire/issues/171#issuecomment-2869519092
