### ISSUE TITLE
 [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by RogerDavidClarke** [Microsoft/BlingFire#18]
Getting the below error after running pip install blingfire (install works fine). Any ideas?

>>> from blingfire import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rogercl\AppData\Local\Programs\Python\Python37-32\lib\site-packages\blingfire\__init__.py", line 16, in <module>
    blingfire = cdll.LoadLibrary(os.path.join(path, "blingfiretokdll.dll"))
  File "C:\Users\rogercl\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\rogercl\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by RogerDavidClarke** [comment]
The problem lies in the platform the DLL was build for. The PIP package has an x64 bit binary which will no work if your Python installation is 32 bit. Just good to be aware of this.

**Comment by SergeiAlonichau** [comment]
Hi,
If you think there is a value supporting x86 platform, we could add amd64_x86 dll as well. I don't mind doing this... 

However could you please let me know what are the scenarios when x86 is needed?

Thank you!
-Sergei
