### ISSUE TITLE
 Unable to load DLL 'blingfiretokdll' or one of its dependencies: 找不到指定的模块。 (0x8007007E) System.DllNotFoundException: Unable to load DLL 'blingfiretokdll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)

### ISSUE THREAD

**Issue by gpww** [microsoft/BlingFire#180]
c#程序启动的时候找不到c++写的DLL 'blingfiretokdll'，这个问题出现在 Windows Server 2022 Datacenter上，而widnows 11 却正常（开发环境，有装visual studio）。dll和c#程序在同一个目录

[08:57:28 ERR] Unable to load DLL 'blingfiretokdll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
System.DllNotFoundException: Unable to load DLL 'blingfiretokdll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
   at BlingFire.BlingFireUtils2.TextToSentences(Byte& inUtf8Str, Int32 inUtf8StrLen, Byte& outBuff, Int32 maxBuffSize)
   at BlingFire.BlingFireUtils2.TextToSentences(Span`1 inUtf8Str, Int32 inUtf8StrLen, Span`1 outBuff, Int32 maxBuffSize) in C:\Users\Silver\.nuget\packages\blingfirenuget\0.1.8\contentFiles\cs\any\BlingFireUtils2.cs:line 164

可能是找不到dll或者什么依赖没有安装？

**Comment by gpww** [comment]
已经解决，装了这个搞定：https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022
